apiVersion: batch/v1
kind: Job
metadata:
  name: current-date
spec:
  template:
    spec:
      containers:
        - image: antham/current-date
          name: current-date
      restartPolicy: Never
